name: CI

on:
  push:
    branches:
      - main
      - enes/speed-up-ci
  pull_request:

jobs:
  ruby-ci:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubicloud-standard-8, ubicloud-standard-8-arm]
    name: Ruby CI - ${{matrix.runs-on}}
    runs-on: ${{matrix.runs-on}}

    env:
      DB_USER: clover
      DB_PASSWORD: nonempty
      DB_NAME: clover_test

    services:
      postgres:
        image: postgres:15.4
        env:
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .tool-versions
        bundler-cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
         node-version-file: "package.json"

    - name: Install node packages
      run: npm ci

    - name: Run erb-formatter
      run: bundle exec rake linter:erb_formatter

    - name: Run rubocop
      run: bundle exec rake linter:rubocop

    - name: Run brakeman
      run: bundle exec rake linter:brakeman

    - name: Run linter:openapi
      run: bundle exec rake linter:openapi

    - name: Run overwrite_envrb
      run: bundle exec rake overwrite_envrb

    - name: Setup database and apply migrations
      run: bundle exec rake setup_database\[test,true\]

    - name: Run annotate
      run: bundle exec rake annotate

    - name: Refresh sequel caches
      run: bundle exec rake refresh_sequel_caches

    - name: Check that source code formatters and annotations make no changes
      run: git diff --stat --exit-code

    - name: Check production puma loads
      run: ruby bin/production_check

    - name: Run controlplane tests
      run: bundle exec rake

    - name: Run dataplane tests
      run: COVERAGE=rhizome bundle exec rspec -O /dev/null rhizome

    - name: Archive code coverage results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report-${{ matrix.runs-on }}
        path: coverage/
